# run --> shift+enter

In [1]:
import numpy as np

In [2]:
a = list(range(1, 11))
a, type(a)

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], list)

In [3]:
arr = np.array(a)
arr, type(arr)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), numpy.ndarray)

In [4]:
# Broadcasting 

print(arr*9)
print(arr+100)
print(arr/5)
print(arr-1)

[ 9 18 27 36 45 54 63 72 81 90]
[101 102 103 104 105 106 107 108 109 110]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr.shape

(10,)

In [6]:
# from vector to 1-D array
arr = arr.reshape(10,1)
arr.shape

(10, 1)

In [7]:
arr = arr.reshape(5, 2)
arr.shape

(5, 2)

In [8]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
d = np.array(a, dtype= float)
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
d[4]

5.0

In [11]:
for i in d :
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [12]:
for i in range(d.shape[0]) :
    print(d[i])

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


## inbuilt function

In [17]:
a = np.zeros((4,3), dtype= int)
print(a.shape)
a

(4, 3)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
a = np.ones((5,8), dtype= int)
print(a.shape)
a

(5, 8)


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
a = np.eye(5, dtype = int)
print(a.shape)
a

(5, 5)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
a = np.zeros((5,4,3,6,7,2))
print(a.shape)
# a

(5, 4, 3, 6, 7, 2)


In [67]:
a = np.ones((5,4), dtype = int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
a.shape

(5, 4)

In [69]:
k = 0
for i in range(a.shape[0]) :
    for j in range(a.shape[1]) :
        a[i][j] += k
        k += 1

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
a = np.array([[1,2,3], 
              [4,5,6]], dtype = float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [71]:
# for i in range(a.shape[0]) : # rows
#     for j in range(i, a.shape[1]) : # col
#         temp = a[j][i]
#         a[j][i] = a[i][j]
#         a[i][j] = temp


temp = []
for i in range(a.shape[1]) : # cols
    x = []
    for j in range(a.shape[0]) :  # rows
        x.append(a[j][i])
    temp.append(x)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
b = np.array(temp)
b

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [55]:
b = a.T # to do transpose of a numpy array
b

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [56]:
np.dot(a,b) # matrix multiplication

array([[ 30,  70, 110, 150],
       [ 70, 174, 278, 382],
       [110, 278, 446, 614],
       [150, 382, 614, 846]])

In [58]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.cross(a, b)

array([-2,  4, -2])

In [61]:
a = a.reshape(3,1)
a

array([[1],
       [2],
       [3]])

In [62]:
b = b.reshape(3,1)
b

array([[3],
       [4],
       [5]])

In [63]:
# corresponding elements get multiplied
a*b

array([[ 3],
       [ 8],
       [15]])

In [64]:
a+b

array([[4],
       [6],
       [8]])

In [65]:
a-b

array([[-2],
       [-2],
       [-2]])

In [66]:
a/b

array([[0.33333333],
       [0.5       ],
       [0.6       ]])